- project:
    templates:
      - golang-jobs
    check:
      jobs:
        - golang-lint
        - network-operator-deployment-images
        - network-operator-integration-centos-8
    gate:
      jobs:
        - golang-lint
        - network-operator-build-image
        - network-operator-deployment-images
        - network-operator-integration-centos-8

- job:
    name: network-operator-build-image
    parent: nuage-build-docker-image
    nodeset: centos-8
    vars:
      vsp_release: "{{ nuage_vsp_release }}"
      builder: operator
      container_command: docker
      zuul_work_dir: "{{ ansible_user_dir }}/src/github.com"
      operator_images:
        - context: nuagenetworks/nuage-network-operator
          repository: nuage/nuage-network-operator

- job:
    name: network-operator-deployment-images
    parent: nuage-build-docker-image
    nodeset: centos-8
    required-projects:
      - gerrit.an.nuagenetworks.net/nuagenetworks/nuage-network-operator
      - gerrit.an.nuagenetworks.net/nuagenetworks/nuage-k8s-infra
      - gerrit.an.nuagenetworks.net/nuagenetworks/nuage-cni
      - gerrit.an.nuagenetworks.net/nuagenetworks/nuage-kubernetes
      - gerrit.an.nuagenetworks.net/nuagenetworks/libvrsdk
    vars:
      vsp_release: "{{ nuage_vsp_release }}"
      container_command: docker
      zuul_work_dir: "{{ ansible_user_dir }}/src/github.com/"
      operator_images:
        - context: nuagenetworks/nuage-network-operator
          repository: nuage/nuage-network-operator
      docker_images:
        - context: nuagenetworks/nuage-k8s-infra
          go_task: build
          repository: nuage/infra
          build_args:
            - "http_proxy={{ proxy_env.http_proxy if proxy_env is defined else '' }}"
            - "https_proxy={{ proxy_env.https_proxy if proxy_env is defined else '' }}"
        - context: nuagenetworks/nuage-cni/
          go_task: make
          repository: nuage/cni
          build_args:
            - "http_proxy={{ proxy_env.http_proxy if proxy_env is defined else '' }}"
            - "https_proxy={{ proxy_env.https_proxy if proxy_env is defined else '' }}"
        - context: nuagenetworks/nuage-kubernetes/nuagekubemon
          go_task: make
          go_makefile: scripts/Makefile
          repository: nuage/monitor

- job:
    name: network-operator-integration-centos-8
    parent: deployment-kubernetes-centos-8
    nodeset: single-node-centos
    dependencies: network-operator-deployment-images
    description: |
      Nuage k8s integration job
    required-projects:
      - gerrit.an.nuagenetworks.net/kubernetes/nuage-container-tests
      - gerrit.an.nuagenetworks.net/nuagenetworks/nuage-k8s-infra
      - gerrit.an.nuagenetworks.net/nuagenetworks/nuage-cni
      - gerrit.an.nuagenetworks.net/nuagenetworks/libvrsdk
    vars:
      vsp_release: "{{ nuage_vsp_release }}"
      cgroupdriver: systemd
      zuul_copy_output:
        '{{ zuul.project.src_dir }}/kube-nuage.yaml': logs
        '{{ zuul.project.src_dir }}/operator-nuageconfig.yaml': logs
        '/var/log/cni': logs
        '/var/log/nuage-openshift-monitor': logs
      kubernetes_pod_network:
        cni: nuage
        cidr: '192.168.0.0/16'
      vsd_user:
        username: k8s-admin
        password: k8s-admin
        groups:
          - 'Administrators'
          - 'Admin Operators'
      default_domain: "ci-{{ zuul.build }}"
