// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.NuageCNIConfig":       schema_pkg_apis_operator_v1alpha1_NuageCNIConfig(ref),
		"github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.NuageCNIConfigSpec":   schema_pkg_apis_operator_v1alpha1_NuageCNIConfigSpec(ref),
		"github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.NuageCNIConfigStatus": schema_pkg_apis_operator_v1alpha1_NuageCNIConfigStatus(ref),
	}
}

func schema_pkg_apis_operator_v1alpha1_NuageCNIConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NuageCNIConfig is the Schema for the networks API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.NuageCNIConfigSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.NuageCNIConfigStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.NuageCNIConfigSpec", "github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.NuageCNIConfigStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_operator_v1alpha1_NuageCNIConfigSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NuageCNIConfigSpec defines the desired state of NuageCNIConfig",
				Properties: map[string]spec.Schema{
					"vrsConfig": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.VRSConfigDefinition"),
						},
					},
					"cniConfig": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.CNIConfigDefinition"),
						},
					},
					"monitorConfig": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.MonitorConfigDefinition"),
						},
					},
					"releaseConfig": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.ReleaseConfigDefinition"),
						},
					},
					"podNetworkConfig": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.PodNetworkConfigDefinition"),
						},
					},
				},
				Required: []string{"vrsConfig", "cniConfig", "monitorConfig", "releaseConfig", "podNetworkConfig"},
			},
		},
		Dependencies: []string{
			"github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.CNIConfigDefinition", "github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.MonitorConfigDefinition", "github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.PodNetworkConfigDefinition", "github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.ReleaseConfigDefinition", "github.com/nuagenetworks/nuage-network-operator/pkg/apis/operator/v1alpha1.VRSConfigDefinition"},
	}
}

func schema_pkg_apis_operator_v1alpha1_NuageCNIConfigStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NuageCNIConfigStatus defines the observed state of NuageCNIConfig",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
